### ISSUE TITLE
Will support Chinese in the future？

### ISSUE THREAD

**Issue by somenzz** [docusealco/docuseal#207] opened 2024-02-06 08:28 UTC
Does docuseal UI support Chinese, and does textfield support Chinese?

**Comment by omohokcoj** [comment] 2024-02-09 18:42
@somenzz yes, but can't give the exact timeline at the moment - closing since that's a duplicate of https://github.com/docusealco/docuseal/issues/148

**Closed by omohokcoj** 2024-02-09 18:42 UTC

**Comment by omohokcoj** [comment] 2024-02-21 00:10
@somenzz  Chinese are supported now in 1.4.4 version
