### ISSUE TITLE
PDF Download missing pages on download

### ISSUE THREAD

**Issue by maaper** [docusealco/docuseal#79] opened 2023-08-09 05:17 UTC
I have an instance of DocuSign running on Docker. 
I have created a document based on two different pages (two different PDF). Both PDF are set together for filling and sign from one single link. 
All is working ok except when I tried to download the signed documents from iOS or iPadOS. In that case the system is giving me only one page and can’t download the second one. 

Perhaps that can be solved in some manner. 

Thanks in advance.

**Comment by maaper** [comment] 2023-08-09 05:31
I have tried it in another browser and confirm what can be a bug. Is not possible to download the second document, system is always returning the first one of the set of two PDF. 

Can you review it?
I can try to record a small video if the description of the issue is not clear enough. 

Thanks in advance.

**Comment by AlexandrToorchyn** [comment] 2023-08-09 20:31
@maaper Thanks for reporting the issue - the bug was caused by a large PDF page size (that's not related to Azure).
I've just pushed a fix into master - it will be available in the 1.1.1 release.

**Comment by maaper** [comment] 2023-08-10 04:00
Perhaps convert two or three documents in one single multipage document for downloading when iOS or iPadOS systems is detected can work. 
??

**Comment by omohokcoj** [comment] 2024-01-02 13:11
@maaper downloading multiple files on ios safari has been fixed in the 1.3.6 release

**Closed by omohokcoj** 2024-01-02 13:11 UTC
