### ISSUE TITLE
FileDropZone not working

### ISSUE THREAD

**Issue by ekadin-mtc** [docusealco/docuseal#136] opened 2023-11-06 22:17 UTC
I added a File field to my form, but nothing happens when I try using it.

**Comment by omohokcoj** [comment] 2023-11-07 00:48
@ekadin-mtc thanks for reporting this. Looks like it was some weird vue bug that appears randomly (i was not able to constantly reproduce it)
https://github.com/docusealco/docuseal/commit/a42ae0b39e7d7ec8f590b95b212258ebab4d828f - I added this fix to ensure that the files array is always defined - it will be released in the next version.

**Comment by ekadin-mtc** [comment] 2023-11-07 15:37
@omohokcoj Thanks for the quick fix! Looking forward to the next release :)

**Comment by omohokcoj** [comment] 2023-11-15 20:45
@ekadin-mtc a new version has been released on Monday - the attachments step should work well there.
Please reopen if the issue still persists in the new version

**Closed by omohokcoj** 2023-11-15 20:45 UTC

**Comment by ekadin-mtc** [comment] 2023-11-15 21:22
Indeed, it works now! Thanks, and keep up the great work!
