### ISSUE TITLE
Inputted date does not match displayed date

### ISSUE THREAD

**Issue by GarrettPeake** [docusealco/docuseal#11] opened 2023-07-20 23:22 UTC
Inputting May 9th on the online demo displays May 8th as shown below, I tested and it always displays the day before. Using `01` as the day will even wrap the month backward.

<img width="588" alt="image" src="https://github.com/docusealco/docuseal/assets/23284777/bbafc42d-ed86-4a53-b3e5-a87abc172386">

**Comment by AlexandrToorchyn** [comment] 2023-07-23 09:45
@GarrettPeake Unfortunately, I was able to reproduce this bug. Could you please provide your browser version and possibly our system timezone? It's a client-side js bug so it might be caused by our specific software environment

**Comment by AlexandrToorchyn** [comment] 2023-08-01 10:37
@GarrettPeake Fixed in release 1.0.8

**Closed by AlexandrToorchyn** 2023-08-01 10:37 UTC
Labels: bug
